project:
  type: website

website:
  title: "Jonas Moss' blog"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JonasMoss
format:
  html:
    theme:
      light: flatly
      dark: darkly
      css: styles.css

editor: visual
execute:
  freeze: auto
